spring:
  application:
    name: demo-book-site
  datasource:
    url: jdbc:mysql://localhost:3306/budget_management_api_demo2
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
      org.springframework.data.jpa.repository: DEBUG

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: lgwc ajdp xxjj cyuq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

email:
  toEmail: ${TO_EMAIL}
  fromEmail: ${FROM_EMAIL}

secret:
  key: ${KEY}

ALGORITHM: ${ALGORITHM}